### ISSUE TITLE
xrandr: failed request:  BadMatch (invalid parameter attributes)

### ISSUE THREAD

**Issue by artist4xlibre** [X11Libre/xserver#2159]
### Select the version

Git master branch

### Describe your issue

Run command: xrandr --output DP-1-1 --primary --mode 2560x1440 --pos 1920x0 --rotate normal --output DP-1-8 --mode 1920x1200 --rotate normal

### Steps to reproduce

Run command: xrandr --output DP-1-1 --primary --mode 2560x1440 --pos 1920x0 --rotate normal --output DP-1-8 --mode 1920x1200 --rotate normal

Errors:
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  142 (RANDR)
  Minor opcode of failed request:  7 (RRSetScreenSize)
  Serial number of failed request:  42
  Current serial number in output stream:  43

### Extra fields

- [x] I have checked the existing [issues](https://github.com/X11Libre/xserver/issues)
- [x] I have read the [Contributing Guidelines](https://github.com/X11Libre/xserver/blob/master/CONTRIBUTING.md)
- [ ] I'd like to work on this issue

**Comment by ghost** [comment]
Additional info: this is happening on physical hardware.

**Comment by cepelinas9000** [comment]
curious @artist4xlibre this xrandr command for  testing? or there are special use case for overlapping output.

**Comment by artist4xlibre** [comment]
There's no overlap; it places the larger display at the right hand side of the smaller one.
This command used to work perfectly with XLibre, but not any longer unfortunately.

**Comment by cepelinas9000** [comment]
> This command used to work perfectly with XLibre

It was working 25.0.x branch? and stoped from 25.1.x first version?

**Comment by artist4xlibre** [comment]
It was working on all Xorg and XLibre releases, including 25.1.3, but no longer from git build.

**Comment by metux** [comment]
> It was working on all Xorg and XLibre releases, including 25.1.3, but no longer from git build.

could you please try to git-bisect it, so we know which commit exactly broke it ?
thx.

**Comment by artist4xlibre** [comment]
I tried with these 3 commits:
a2976e302377910a3948f4a13c7a7721e392217a
7ffd763439990f18f2045e6bb1f0937085ef6e6c
f5295b8d3611aedc556ecbdcb9fc3bcc0bb4002e

For all I get this build error:
```
[325/711] Compiling C object hw/xfree86/common/libxorg_common.a.p/xf86pciBus.c.o
FAILED: [code=1] hw/xfree86/common/libxorg_common.a.p/xf86pciBus.c.o 
cc -Ihw/xfree86/common/libxorg_common.a.p -Ihw/xfree86/common -I../xserver/hw/xfree86/common -I. -I../xserver -IXext -I../xserver/Xext -IXext/dri2 -I../xserver/Xext/dri2 -IXi -I../xserver/Xi -Icomposite -I../xserver/composite -Iexa -I../xserver/exa -Ifb -I../xserver/fb -Iglamor -I../xserver/glamor -Imi -I../xserver/mi -Imiext/damage -I../xserver/miext/damage -Imiext/shadow -I../xserver/miext/shadow -Imiext/sync -I../xserver/miext/sync -Idbe -I../xserver/dbe -Idix -I../xserver/dix -Idri3 -I../xserver/dri3 -Iinclude -I../xserver/include -Ipresent -I../xserver/present -Irandr -I../xserver/randr -Irender -I../xserver/render -Ixfixes -I../xserver/xfixes -Ihw/xfree86/ddc -I../xserver/hw/xfree86/ddc -Ihw/xfree86/i2c -I../xserver/hw/xfree86/i2c -Ihw/xfree86/int10 -I../xserver/hw/xfree86/int10 -Ihw/xfree86/loader -I../xserver/hw/xfree86/loader -Ihw/xfree86/modes -I../xserver/hw/xfree86/modes -Ihw/xfree86/os-support -I../xserver/hw/xfree86/os-support -I../xserver/hw/xfree86/os-support/bus -Ihw/xfree86/parser -I../xserver/hw/xfree86/parser -Ihw/xfree86/ramdac -I../xserver/hw/xfree86/ramdac -Ihw/xfree86/vgahw -I../xserver/hw/xfree86/vgahw -I/usr/include/X11/dri -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/elogind -I/usr/include/libdrm -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=gnu99 -O3 -fno-strict-aliasing -fvisibility=hidden -Wvla -fno-common -Wshift-negative-value -Wchar-subscripts -Wall -Wchar-subscripts -Wpointer-arith -Wmissing-declarations -Wformat=2 -Wstrict-prototypes -Wmissing-prototypes -Wnested-externs -Wbad-function-cast -Wold-style-definition -Wunused -Wuninitialized -Wshadow -Wmissing-noreturn -Wmissing-format-attribute -Wredundant-decls -Werror=implicit -Werror=nonnull -Werror=init-self -Werror=main -Werror=missing-braces -Werror=sequence-point -Werror=return-type -Werror=trigraphs -Werror=array-bounds -Werror=write-strings -Werror=address -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -Woverride-init -Wvla -Wincompatible-pointer-types -march=x86-64 -mtune=generic -O2 -pipe -fexceptions -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -flto=auto -fPIC -DHAVE_XORG_CONFIG_H -DXORG_NO_SDKSYMS '-DXORG_MODULE_ABI_TAG="xlibre-25"' '-DFALLBACK_INPUT_DRIVER="libinput"' -MD -MQ hw/xfree86/common/libxorg_common.a.p/xf86pciBus.c.o -MF hw/xfree86/common/libxorg_common.a.p/xf86pciBus.c.o.d -o hw/xfree86/common/libxorg_common.a.p/xf86pciBus.c.o -c ../xserver/hw/xfree86/common/xf86pciBus.c
In file included from ../xserver/hw/xfree86/common/xf86pciBus.c:42:
../xserver/hw/xfree86/common/xf86_pci_priv.h:22:19: error: static declaration of ‘pci_device_is_boot_display’ follows non-static declaration
   22 | static inline int pci_device_is_boot_display(struct pci_device *dev)
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../xserver/hw/xfree86/common/xf86pciBus.c:36:
/usr/include/pciaccess.h:83:5: note: previous declaration of ‘pci_device_is_boot_display’ with type ‘int(struct pci_device *)’
   83 | int pci_device_is_boot_display(struct pci_device *dev);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by cepelinas9000** [comment]
> I tried with these 3 commits: [a2976e3](https://github.com/X11Libre/xserver/commit/a2976e302377910a3948f4a13c7a7721e392217a) [7ffd763](https://github.com/X11Libre/xserver/commit/7ffd763439990f18f2045e6bb1f0937085ef6e6c) [f5295b8](https://github.com/X11Libre/xserver/commit/f5295b8d3611aedc556ecbdcb9fc3bcc0bb4002e)
> 
> For all I get this build error:
> 
> ```
> [325/711] Compiling C object hw/xfree86/common/libxorg_common.a.p/xf86pciBus.c.o
> FAILED: [code=1] hw/xfree86/common/libxorg_common.a.p/xf86pciBus.c.o 
> cc -Ihw/xfree86/common/libxorg_common.a.p -Ihw/xfree86/common -I../xserver/hw/xfree86/common -I. -I../xserver -IXext -I../xserver/Xext -IXext/dri2 -I../xserver/Xext/dri2 -IXi -I../xserver/Xi -Icomposite -I../xserver/composite -Iexa -I../xserver/exa -Ifb -I../xserver/fb -Iglamor -I../xserver/glamor -Imi -I../xserver/mi -Imiext/damage -I../xserver/miext/damage -Imiext/shadow -I../xserver/miext/shadow -Imiext/sync -I../xserver/miext/sync -Idbe -I../xserver/dbe -Idix -I../xserver/dix -Idri3 -I../xserver/dri3 -Iinclude -I../xserver/include -Ipresent -I../xserver/present -Irandr -I../xserver/randr -Irender -I../xserver/render -Ixfixes -I../xserver/xfixes -Ihw/xfree86/ddc -I../xserver/hw/xfree86/ddc -Ihw/xfree86/i2c -I../xserver/hw/xfree86/i2c -Ihw/xfree86/int10 -I../xserver/hw/xfree86/int10 -Ihw/xfree86/loader -I../xserver/hw/xfree86/loader -Ihw/xfree86/modes -I../xserver/hw/xfree86/modes -Ihw/xfree86/os-support -I../xserver/hw/xfree86/os-support -I../xserver/hw/xfree86/os-support/bus -Ihw/xfree86/parser -I../xserver/hw/xfree86/parser -Ihw/xfree86/ramdac -I../xserver/hw/xfree86/ramdac -Ihw/xfree86/vgahw -I../xserver/hw/xfree86/vgahw -I/usr/include/X11/dri -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/elogind -I/usr/include/libdrm -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=gnu99 -O3 -fno-strict-aliasing -fvisibility=hidden -Wvla -fno-common -Wshift-negative-value -Wchar-subscripts -Wall -Wchar-subscripts -Wpointer-arith -Wmissing-declarations -Wformat=2 -Wstrict-prototypes -Wmissing-prototypes -Wnested-externs -Wbad-function-cast -Wold-style-definition -Wunused -Wuninitialized -Wshadow -Wmissing-noreturn -Wmissing-format-attribute -Wredundant-decls -Werror=implicit -Werror=nonnull -Werror=init-self -Werror=main -Werror=missing-braces -Werror=sequence-point -Werror=return-type -Werror=trigraphs -Werror=array-bounds -Werror=write-strings -Werror=address -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -Woverride-init -Wvla -Wincompatible-pointer-types -march=x86-64 -mtune=generic -O2 -pipe -fexceptions -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -flto=auto -fPIC -DHAVE_XORG_CONFIG_H -DXORG_NO_SDKSYMS '-DXORG_MODULE_ABI_TAG="xlibre-25"' '-DFALLBACK_INPUT_DRIVER="libinput"' -MD -MQ hw/xfree86/common/libxorg_common.a.p/xf86pciBus.c.o -MF hw/xfree86/common/libxorg_common.a.p/xf86pciBus.c.o.d -o hw/xfree86/common/libxorg_common.a.p/xf86pciBus.c.o -c ../xserver/hw/xfree86/common/xf86pciBus.c
> In file included from ../xserver/hw/xfree86/common/xf86pciBus.c:42:
> ../xserver/hw/xfree86/common/xf86_pci_priv.h:22:19: error: static declaration of ‘pci_device_is_boot_display’ follows non-static declaration
>    22 | static inline int pci_device_is_boot_display(struct pci_device *dev)
>       |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~
> In file included from ../xserver/hw/xfree86/common/xf86pciBus.c:36:
> /usr/include/pciaccess.h:83:5: note: previous declaration of ‘pci_device_is_boot_display’ with type ‘int(struct pci_device *)’
>    83 | int pci_device_is_boot_display(struct pci_device *dev);
>       |     ^~~~~~~~~~~~~~~~~~~~~~~~~~
> ```

* sometimes you need to remove `build` directory and try again compilation (start build directory from clean state)
* on non compiling commits you can use `git bisect skip`
* or on lucky cases fix them. (this error - you can delete duplicate declaration)

**Comment by artist4xlibre** [comment]
I only build in clean chroots.

The error is: 

```
../xserver/hw/xfree86/common/xf86_pci_priv.h:22:19: error: static declaration of
‘pci_device_is_boot_display’ follows non-static declaration
   22 | static inline int pci_device_is_boot_display(struct pci_device *dev)
```

What should be removed exactly? Can you pls provide a git diff for this? Then I'll add it as a patch to the build.

**Comment by artist4xlibre** [comment]
f5295b8 builds and works fine now; I'll continue bisecting

**Comment by artist4xlibre** [comment]
This is the problematic commit: e2550d0 "randr: do full transform when checking SetScreenSize size"

Probably [L281/L282](https://github.com/X11Libre/xserver/blob/e2550d065b731f3f163725065d1db9522622e91c/randr/rrscreen.c#L281)

**Comment by artist4xlibre** [comment]
This patch fixes the problem but I am not sure the logic is correct:

```
--- a/randr/rrscreen.c	2026-04-11 11:19:11.856254169 +0200
+++ b/randr/rrscreen.c	2026-04-11 12:33:20.808831474 +0200
@@ -278,7 +278,9 @@
             };
             pixman_f_transform_bounds(&crtc->f_transform, &display_box);
 
-            if (display_box.x2 > stuff->width || display_box.y2 > stuff->height)
+            /* if (display_box.x2 > stuff->width || display_box.y2 > stuff->height) */
+            if (crtc->x + mode->mode.width > stuff->width ||
+                crtc->y + mode->mode.height > stuff->height)
                 return BadMatch;
         }
     }
```

**Comment by callmetango** [comment]
@artist4xlibre Could you please verify the issue has been resolved?

**Comment by ghost** [comment]
Issue is fixed both both release 25.0 and 25.1
