### ISSUE TITLE
xf86-input-wacom fails to build

### ISSUE THREAD

**Issue by drfiemost** [X11Libre/xserver#751]
### Select the version

25.0.0.X

### Describe your issue

Trying to compile _xf86-input-wacom_ and I get this error:
```
../src/x11/xf86Wacom.c: In function 'wcmLog':
../src/x11/xf86Wacom.c:74:9: error: implicit declaration of function 'xf86VIDrvMsgVerb'; did you mean 'xf86IDrvMsgVerb'? [-Wimplicit-function-declaration]
   74 |         xf86VIDrvMsgVerb(priv->frontend, xtype, 0, format, args);
      |         ^~~~~~~~~~~~~~~~
      |         xf86IDrvMsgVerb
```

### Steps to reproduce

Download [latest xf86-input-wacom release](https://github.com/linuxwacom/xf86-input-wacom/releases/tag/xf86-input-wacom-1.2.3) and build with `./configure && make`

### What did you expect?

Successful build

### Additional Information

Seems caused by https://github.com/X11Libre/xserver/commit/21849176463a8c25f22e07c97824d08d546355e0

### Extra fields

- [x] I have checked the existing [issues](https://github.com/X11Libre/xserver/issues)
- [x] I have read the [Contributing Guidelines](https://github.com/X11Libre/xserver/blob/master/CONTRIBUTING.md)
- [ ] I'd like to work on this issue

**Comment by drfiemost** [comment]
Oops, just found out https://github.com/X11Libre/xf86-input-wacom, I'll give it a try...

**Comment by callmetango** [comment]
> Oops, just found out https://github.com/X11Libre/xf86-input-wacom, I'll give it a try...

This should really fix your problem. Please report back and also see [Device Dependent X (DDX) Drivers · Compatibility of XLibre · X11Libre/xserver Wiki](https://github.com/X11Libre/xserver/wiki/Compatibility-of-XLibre#device-dependent-x-ddx-drivers).
